//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorkemAydogduProje.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GA_StajProjeEntities : DbContext
    {
        public GA_StajProjeEntities()
            : base("name=GA_StajProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Calisan> tbl_Calisan { get; set; }
        public virtual DbSet<tbl_Is> tbl_Is { get; set; }
        public virtual DbSet<tbl_IsAciklama> tbl_IsAciklama { get; set; }
        public virtual DbSet<tbl_Proje> tbl_Proje { get; set; }
    }
}
