//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorkemAydogduProje.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Is
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Is()
        {
            this.tbl_IsAciklama = new HashSet<tbl_IsAciklama>();
        }
    
        public int Id { get; set; }
        public string IsAdi { get; set; }
        public Nullable<int> Proje { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string Durumu { get; set; }
    
        public virtual tbl_Proje tbl_Proje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IsAciklama> tbl_IsAciklama { get; set; }
    }
}
